# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tech Tree Interactive Demo
email: boru.design@gmail.com
description: Tech Tree Interactive Demo @ Stitch Fix
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yorthehunter.github.io" # the base hostname & protocol for your site
baseurl: "/tech-tree-output"
twitter_username: yor_the_hunter
github_username:  yorthehunter

# Build settings
markdown: kramdown
